version: '3.9'

services:
  ntp:
    image: snowy68/ntp:latest
    container_name: ntp
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    ports:
      - 123:123/udp
    volumes:
      - ./chrony.conf:/etc/chrony/chrony.conf:ro
#    environment:
#      - TZ=America/Vancouver